Print a nicer error when the input is missing

diff --git a/.github/workflows/add-to-project.yml b/.github/workflows/add-to-project.yml
--- a/.github/workflows/add-to-project.yml
+++ b/.github/workflows/add-to-project.yml
@@ -30,6 +30,11 @@ jobs:
     name: Add issue to project
     runs-on: ubuntu-latest
     steps:
+      - name: Fail if project-url is not set
+        if: env.PROJECT_URL == ''
+        run: |
+          echo "The project-url input is required."
+          exit 1
       - uses: actions/add-to-project@v1.0.2
         with:
           project-url: ${{ env.PROJECT_URL }}
