Add missing input message

diff --git a/.github/workflows/add-to-project.yml b/.github/workflows/add-to-project.yml
--- a/.github/workflows/add-to-project.yml
+++ b/.github/workflows/add-to-project.yml
@@ -37,6 +37,11 @@ jobs:
         run: |
           echo "The project-url input is required."
           exit 1
+      - name: Fail if GITHUB_PAT is not set
+        if: env.GITHUB_TOKEN == ''
+        run: |
+          echo "The GITHUB_PAT input is required."
+          exit 1
       - uses: actions/add-to-project@v1.0.2
         with:
           project-url: ${{ env.PROJECT_URL }}
